[package]
name = "blockchain-contract-meta"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies.blockchain-contract]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.1"
default-features = false
